---
title: "Project 3 - Boosting Script"
author: "Huijun Cui"
date: "March 1, 2018"
output:
  pdf_document: default
  html_document: default
---

```{r, warning = FALSE}
if(!require("EBImage")){
  source("https://bioconductor.org/biocLite.R")
  biocLite("EBImage")
}

if(!require("gbm")){
  install.packages("gbm")
}

if(!require("pbapply")){
  install.packages("pbapply")
}

if(!require("sets")){
  install.packages("sets")
}

if(!require("tree")){
  install.packages("tree")
}

if(!require("randomForest")){
  install.packages("randomForest")
}

library("sets")
library("pbapply")
library("dplyr")
library("purrr")
library("EBImage")
library("gbm")
library("tidyverse")
library("grDevices")
library("gbm")
```

```{r wkdir, eval=FALSE}
setwd("C:/Users/Admin/Documents/GitHub/project-2-predictive-modelling-group-1/doc") 
```

```{r}
img_train_dir  <- "../data/pets/train/"
```

```{r train_label}
labels <- read.table(paste(img_train_dir, "../train_label.txt", sep = ""), header = F)
label <- as.numeric(unlist(labels) == "dog")
```

```{r}
features <- read.csv("../output/sift_features.csv", sep = ",", header=F)
mydata <- data.frame(features,label)
```

```{r}
set.seed(4)
train=sample(1:nrow(mydata),nrow(mydata)*0.8)
mydata.test=mydata[-train,]
label.test=label[-train]
```

```{r}
set.seed(10)
boost.mydata = gbm(label~.,data=mydata[train,], distribution=
"bernoulli",n.trees = 4000, interaction.depth = 4)

yhat.boost=predict(boost.mydata,newdata=mydata[-train,],
n.trees = 4000)
mean((yhat.boost - mydata.test)^2)
```
