---
title: "Project 2 - KNN (BOWmatrix_std-200)"
author: "Huijun Cui"
date: "March 3, 2018"
output:
  pdf_document: default
  html_document: default
---

```{r, warning = FALSE}
if(!require("sets")){
  install.packages("sets")
}

if(!require("tree")){
  install.packages("tree")
}

if(!require("randomForest")){
  install.packages("randomForest")
}

library("sets")
library("pbapply")
library("dplyr")
library("purrr")
library("EBImage")
library("gbm")
library("tidyverse")
library("grDevices")
library("class")
```

### Step 1: Set path

```{r wkdir, eval=FALSE}
setwd("C:/Users/Admin/Documents/GitHub/project-2-predictive-modelling-group-1/doc") 

img_train_dir  <- "../data/pets/train/"
```

### Step 2: Import training images class labels.

```{r train_label}
labels <- read.table(paste(img_train_dir, "../train_label.txt", sep = ""), header = F)
labels <- ifelse(labels == "dog", 'dog', 'cat')
label <- as.factor(labels) 
```

### Step 3: Importing SIFT features

```{r}
features <- read.csv("../lib/BOWmatrix_std-200.csv", sep = ",", header=T)
feature <- features[,-1]
mydata <- data.frame(feature,label)
stdfeature <- scale(feature)
#head(stdfeature)
```

### Step 4: Model training and predicting

```{r}
set.seed(6)
train=sample(1:nrow(stdfeature),nrow(stdfeature)*0.8)
stdfeature.train=stdfeature[train,]
stdfeature.test=stdfeature[-train,]
label.train=label[train]
label.test=label[-train]

knn.pred=knn(stdfeature.train,stdfeature.test,label.train,k=105)
cmatrix = table(knn.pred,label.test)
```

### Step 5: Prediction results presentation

```{r}
cmatrix
accuracy = sum(cmatrix[1,1]+cmatrix[2,2])/(2000*0.2)
accuracy
```
