---
title: "Project 2 - Random Forest for Classification (BOWmatrix-50)"
author: "Huijun Cui"
date: "March 2, 2018"
output:
  pdf_document: default
  html_document: default
---

```{r, warning = FALSE}
if(!require("sets")){
  install.packages("sets")
}

if(!require("tree")){
  install.packages("tree")
}

if(!require("randomForest")){
  install.packages("randomForest")
}

library("sets")
library("pbapply")
library("dplyr")
library("purrr")
library("EBImage")
library("gbm")
library("tidyverse")
library("grDevices")
library("tree")
```

### Step 1: Set path

```{r wkdir, eval=FALSE}
setwd("C:/Users/Admin/Documents/GitHub/project-2-predictive-modelling-group-1/doc") 

img_train_dir  <- "../data/pets/train/"
```

### Step 2: Import training images class labels.

```{r train_label}
labels <- read.table(paste(img_train_dir, "../train_label.txt", sep = ""), header = F)
labels <- ifelse(labels == "dog", 'dog', 'cat')
label <- as.factor(labels) 
```

### Step 3: Importing SIFT features

```{r}
features <- read.csv("../lib/BOWmatrix-50.csv", sep = ",", header=T)
feature <- features[,-1]
mydata <- data.frame(feature,label)
head(mydata)
```

### Step 4: Model training and predicting

```{r}
set.seed(6)
train=sample(1:nrow(mydata),nrow(mydata)*0.8)
mydata.test=mydata[-train,]
label.test=label[-train]
tree.mydata =tree(label~.,mydata,subset=train)
tree.pred=predict(tree.mydata,mydata.test,type ="class")
cmatrix = table(tree.pred,label.test)
```

### Step 5: Prediction results presentation

```{r}
cmatrix
accuracy = sum(cmatrix[1,1]+cmatrix[2,2])/(2000*0.2)
accuracy
```

### Step 6: Cross Validation

```{r}
set.seed(1)
cv.mydata<-cv.tree(tree.mydata, FUN=prune.misclass)
names(cv.mydata)
cv.mydata
plot(cv.mydata$size,cv.mydata$dev,type="b")
plot(cv.mydata$k ,cv.mydata$dev ,type="b")
```

### Step 7: Pruning and remodel

```{r}
prune.mydata=prune.misclass(tree.mydata,best=3)
plot(prune.mydata)
text(prune.mydata,pretty=0)
tree.pred=predict(prune.mydata,mydata.test,type="class")
cpmatrix<-table(tree.pred,label.test)
cpmatrix
paccuracy = sum(cpmatrix[1,1]+cpmatrix[2,2])/(2000*0.2)
paccuracy
```

